/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleAgenciaFazendaria;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModeloAgenciaFazendaria;
import model.ModeloContato;
import model.ModeloEndereco;

/**
 *
 * @author Scorsatto
 */
public class TelaEndereco extends javax.swing.JDialog {

    private ArrayList<ModeloAgenciaFazendaria> lstAgenciaFazendaria;
    private String acao = "";
    private boolean atualizarComboBox = false;

    /**
     * Creates new form TelaEndereco
     *
     * @param parent
     * @param modal
     */
    public TelaEndereco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.organizaBotoes("abreTela");
        this.montaTelaPesquisa();
    }

    public boolean atualizarDados() {
        return atualizarComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPesquisa = new javax.swing.ButtonGroup();
        jtpEndereco = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stfSigla = new br.com.util.scorsatto.componentes.STextField();
        stfNome = new br.com.util.scorsatto.componentes.STextField();
        stfUnidadeSuperior = new br.com.util.scorsatto.componentes.STextField();
        stfArea = new br.com.util.scorsatto.componentes.STextField();
        stfOrgao = new br.com.util.scorsatto.componentes.STextField();
        stfResponsavel = new br.com.util.scorsatto.componentes.STextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        stfLogradouro = new br.com.util.scorsatto.componentes.STextField();
        stfNumero = new br.com.util.scorsatto.componentes.STextField();
        stfBairro = new br.com.util.scorsatto.componentes.STextField();
        stfComplemento = new br.com.util.scorsatto.componentes.STextField();
        stfPontoReferencia = new br.com.util.scorsatto.componentes.STextField();
        stfMunicipio = new br.com.util.scorsatto.componentes.STextField();
        stfUF = new br.com.util.scorsatto.componentes.STextField();
        stfCEP = new br.com.util.scorsatto.componentes.SCEP();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stfTelefone = new br.com.util.scorsatto.componentes.SFone();
        stfFax = new br.com.util.scorsatto.componentes.SFone();
        stfCaixaPostal = new br.com.util.scorsatto.componentes.STextField();
        stfEmail = new br.com.util.scorsatto.componentes.STextField();
        jPanel4 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jrbSigla = new javax.swing.JRadioButton();
        jrbNome = new javax.swing.JRadioButton();
        stfPesquisa = new br.com.util.scorsatto.componentes.STextField();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisaAgenciaFazendaria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SEFAZ - Endereços");
        setResizable(false);

        jtpEndereco.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da Unidade Fazendária"));

        jLabel5.setText("Sigla:");

        jLabel6.setText("Nome:");

        jLabel7.setText("Unidade Superior:");

        jLabel8.setText("Área:");

        jLabel9.setText("Órgão:");

        jLabel10.setText("Responsável:");

        stfSigla.setSTamanhoMax(10);
        stfSigla.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfSigla.setEnabled(false);

        stfNome.setSTamanhoMax(75);
        stfNome.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfNome.setEnabled(false);

        stfUnidadeSuperior.setSTamanhoMax(10);
        stfUnidadeSuperior.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfUnidadeSuperior.setEnabled(false);

        stfArea.setSTamanhoMax(75);
        stfArea.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfArea.setEnabled(false);

        stfOrgao.setSTamanhoMax(75);
        stfOrgao.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfOrgao.setEnabled(false);

        stfResponsavel.setSTamanhoMax(75);
        stfResponsavel.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfResponsavel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(stfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(stfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addComponent(stfUnidadeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stfArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {stfArea, stfNome, stfOrgao});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {stfSigla, stfUnidadeSuperior});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(stfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stfUnidadeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(stfArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel11.setText("Logradouro:");

        jLabel12.setText("Número:");

        jLabel13.setText("Bairro:");

        jLabel14.setText("Complemento:");

        jLabel15.setText("Ponto de Referência:");

        jLabel16.setText("Município:");

        jLabel17.setText("UF:");

        jLabel18.setText("CEP:");

        stfLogradouro.setSTamanhoMax(75);
        stfLogradouro.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfLogradouro.setEnabled(false);

        stfNumero.setSTamanhoMax(10);
        stfNumero.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfNumero.setEnabled(false);

        stfBairro.setSTamanhoMax(75);
        stfBairro.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfBairro.setEnabled(false);

        stfComplemento.setSTamanhoMax(75);
        stfComplemento.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfComplemento.setEnabled(false);

        stfPontoReferencia.setSTamanhoMax(75);
        stfPontoReferencia.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfPontoReferencia.setEnabled(false);

        stfMunicipio.setSTamanhoMax(75);
        stfMunicipio.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfMunicipio.setEnabled(false);

        stfUF.setSTamanhoMax(2);
        stfUF.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.SOMENTE_TEXTO);
        stfUF.setEnabled(false);

        stfCEP.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stfPontoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(stfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(stfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(stfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(stfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(stfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(stfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(stfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(stfPontoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        jLabel1.setText("Telefone:");

        jLabel2.setText("Fax:");

        jLabel3.setText("Caixa Postal:");

        jLabel4.setText("E-Mail:");

        stfTelefone.setEnabled(false);

        stfFax.setEnabled(false);

        stfCaixaPostal.setSTamanhoMax(11);
        stfCaixaPostal.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfCaixaPostal.setEnabled(false);

        stfEmail.setSTamanhoMax(75);
        stfEmail.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfEmail.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfFax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfCaixaPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(stfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(stfCaixaPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_remove.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_ok.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button_cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnGravar, btnNovo});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnGravar)
                    .addComponent(btnCancelar)
                    .addComponent(btnFechar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEndereco.addTab("Cadastro", jPanelCadastro);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("Pesquisar:");

        grupoPesquisa.add(jrbSigla);
        jrbSigla.setSelected(true);
        jrbSigla.setText("Sigla");

        grupoPesquisa.add(jrbNome);
        jrbNome.setText("Nome");

        stfPesquisa.setSTamanhoMax(75);
        stfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfPesquisaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jrbNome)
                                .addGap(18, 18, 18)
                                .addComponent(stfPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jrbSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSigla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbNome)
                    .addComponent(stfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablePesquisaAgenciaFazendaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nome", "Responsável"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePesquisaAgenciaFazendaria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePesquisaAgenciaFazendaria.getTableHeader().setReorderingAllowed(false);
        tablePesquisaAgenciaFazendaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaAgenciaFazendariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePesquisaAgenciaFazendaria);
        if (tablePesquisaAgenciaFazendaria.getColumnModel().getColumnCount() > 0) {
            tablePesquisaAgenciaFazendaria.getColumnModel().getColumn(0).setResizable(false);
            tablePesquisaAgenciaFazendaria.getColumnModel().getColumn(1).setResizable(false);
            tablePesquisaAgenciaFazendaria.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpEndereco.addTab("Pesquisa", jPanelPesquisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEndereco)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEndereco)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.organizaBotoes("novo");

        this.acao = "novoRegistro";
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.organizaBotoes("cancelar");
        this.limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        this.organizaBotoes("gravar");

        if (acao.equals("novoRegistro")) {
            if (new ControleAgenciaFazendaria().incluirAgenciaFazendaria(getObjAgencia(null)) > 0) {
                limparCampos();
            }
        } else {
            if(new ControleAgenciaFazendaria().alterarAgenciaFazendaria(getObjAgencia(lstAgenciaFazendaria.get(tablePesquisaAgenciaFazendaria.getSelectedRow())))){
                limparCampos();
            }
        }
        
        atualizarComboBox = true;
    }//GEN-LAST:event_btnGravarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        montaTelaPesquisa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablePesquisaAgenciaFazendariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaAgenciaFazendariaMouseClicked
        if (evt.getClickCount() == 2) {
            jtpEndereco.setSelectedIndex(0);

            this.povoaCampos(lstAgenciaFazendaria.get(tablePesquisaAgenciaFazendaria.getSelectedRow()));

            this.organizaBotoes("dadoSelecionado");
            this.btnAlterar.grabFocus();
            this.jtpEndereco.setEnabled(false);
        }
    }//GEN-LAST:event_tablePesquisaAgenciaFazendariaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String agencia = stfSigla.getText() + " - " + stfNome.getText();
        
        Object[] optionsDeletaCadastro = {"    Sim    ", "    NÃ£o    "};
        if (JOptionPane.showOptionDialog(null, "Deseja excluir\n" + agencia + "?", "Excluir AgÃªncia FazendÃ¡ria", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, optionsDeletaCadastro, optionsDeletaCadastro[1]) == 0) {

            new ControleAgenciaFazendaria().excluirAgenciaFazendaria(lstAgenciaFazendaria.get(tablePesquisaAgenciaFazendaria.getSelectedRow()));
            this.montaTelaPesquisa();
            this.limparCampos();
            this.organizaBotoes("abreTela");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        this.acao = "alterarRegisto";
        this.organizaBotoes("alterar");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void stfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfPesquisaActionPerformed
        montaTelaPesquisa();
    }//GEN-LAST:event_stfPesquisaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.ButtonGroup grupoPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbNome;
    private javax.swing.JRadioButton jrbSigla;
    private javax.swing.JTabbedPane jtpEndereco;
    private br.com.util.scorsatto.componentes.STextField stfArea;
    private br.com.util.scorsatto.componentes.STextField stfBairro;
    private br.com.util.scorsatto.componentes.SCEP stfCEP;
    private br.com.util.scorsatto.componentes.STextField stfCaixaPostal;
    private br.com.util.scorsatto.componentes.STextField stfComplemento;
    private br.com.util.scorsatto.componentes.STextField stfEmail;
    private br.com.util.scorsatto.componentes.SFone stfFax;
    private br.com.util.scorsatto.componentes.STextField stfLogradouro;
    private br.com.util.scorsatto.componentes.STextField stfMunicipio;
    private br.com.util.scorsatto.componentes.STextField stfNome;
    private br.com.util.scorsatto.componentes.STextField stfNumero;
    private br.com.util.scorsatto.componentes.STextField stfOrgao;
    private br.com.util.scorsatto.componentes.STextField stfPesquisa;
    private br.com.util.scorsatto.componentes.STextField stfPontoReferencia;
    private br.com.util.scorsatto.componentes.STextField stfResponsavel;
    private br.com.util.scorsatto.componentes.STextField stfSigla;
    private br.com.util.scorsatto.componentes.SFone stfTelefone;
    private br.com.util.scorsatto.componentes.STextField stfUF;
    private br.com.util.scorsatto.componentes.STextField stfUnidadeSuperior;
    private javax.swing.JTable tablePesquisaAgenciaFazendaria;
    // End of variables declaration//GEN-END:variables

    private void montaTelaPesquisa() {
        String campo;

        if (jrbSigla.isSelected()) {
            campo = "sigla_uni";
        } else {
            campo = "nome_uni";
        }

        ControleAgenciaFazendaria controleAgencia = new ControleAgenciaFazendaria();
        lstAgenciaFazendaria = controleAgencia.pesquisaAgenciaFazendaria(stfPesquisa.getText(), campo);
        DefaultTableModel dtm = (DefaultTableModel) tablePesquisaAgenciaFazendaria.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i <= lstAgenciaFazendaria.size() - 1; i++) {
            dtm.addRow(new Object[]{lstAgenciaFazendaria.get(i).getSigla(),
                lstAgenciaFazendaria.get(i).getNome(),
                lstAgenciaFazendaria.get(i).getResponsavel()});
        }
    }

    private void organizaBotoes(String acao) {

        switch (acao) {
            case "abreTela":
                this.btnNovo.setEnabled(true);
                this.btnAlterar.setEnabled(false);
                this.btnExcluir.setEnabled(false);
                this.btnGravar.setEnabled(false);
                this.btnCancelar.setEnabled(false);
                this.btnFechar.setEnabled(true);
                this.jtpEndereco.setEnabled(true);
                break;
            case "novo":
                this.btnNovo.setEnabled(false);
                this.btnAlterar.setEnabled(false);
                this.btnExcluir.setEnabled(false);
                this.btnGravar.setEnabled(true);
                this.btnCancelar.setEnabled(true);
                this.btnFechar.setEnabled(false);
                this.habilitarCampos(true);
                break;
            case "cancelar":
                this.organizaBotoes("abreTela");
                this.habilitarCampos(false);
                break;
            case "gravar":
                this.organizaBotoes("abreTela");
                this.habilitarCampos(false);
                break;
            case "alterar":
                this.organizaBotoes("novo");
                break;
            case "dadoSelecionado":
                this.btnNovo.setEnabled(false);
                this.btnAlterar.setEnabled(true);
                this.btnExcluir.setEnabled(true);
                this.btnGravar.setEnabled(false);
                this.btnCancelar.setEnabled(true);
                this.btnFechar.setEnabled(true);
                break;
            default:
                break;
        }
    }

    private void habilitarCampos(boolean habilitar) {
        this.stfSigla.setEnabled(habilitar);

        if (habilitar) {
            this.stfSigla.grabFocus();
        }

        this.stfNome.setEnabled(habilitar);
        this.stfUnidadeSuperior.setEnabled(habilitar);
        this.stfArea.setEnabled(habilitar);
        this.stfOrgao.setEnabled(habilitar);
        this.stfResponsavel.setEnabled(habilitar);
        //---
        this.stfLogradouro.setEnabled(habilitar);
        this.stfNumero.setEnabled(habilitar);
        this.stfBairro.setEnabled(habilitar);
        this.stfMunicipio.setEnabled(habilitar);
        this.stfUF.setEnabled(habilitar);
        this.stfCEP.setEnabled(habilitar);
        this.stfComplemento.setEnabled(habilitar);
        this.stfPontoReferencia.setEnabled(habilitar);
        //---
        this.stfTelefone.setEnabled(habilitar);
        this.stfFax.setEnabled(habilitar);
        this.stfCaixaPostal.setEnabled(habilitar);
        this.stfEmail.setEnabled(habilitar);
    }

    private ModeloAgenciaFazendaria getObjAgencia(ModeloAgenciaFazendaria objAgenciaFazendaria) {

        ModeloEndereco objEndereco;
        ModeloContato objContato;
        
        if (objAgenciaFazendaria == null){
            objAgenciaFazendaria = new ModeloAgenciaFazendaria();
            objEndereco = new ModeloEndereco();
            objContato = new ModeloContato();
        } else {
            objEndereco = objAgenciaFazendaria.getEndereco();
            objContato = objAgenciaFazendaria.getContato();
        }
        
        // Inclui Agencia
        objAgenciaFazendaria.setSigla(stfSigla.getText());
        objAgenciaFazendaria.setNome(stfNome.getText());
        objAgenciaFazendaria.setUnidadeSuperior(stfUnidadeSuperior.getText());
        objAgenciaFazendaria.setArea(stfArea.getText());
        objAgenciaFazendaria.setOrgao(stfOrgao.getText());
        objAgenciaFazendaria.setResponsavel(stfResponsavel.getText());

        // Inclui EndereÃ§o
        objEndereco.setLogradouro(stfLogradouro.getText());
        objEndereco.setNumero(stfNumero.getText());
        objEndereco.setBairro(stfBairro.getText());
        objEndereco.setMunicipio(stfMunicipio.getText());
        objEndereco.setUf(stfUF.getText());
        objEndereco.setCep(stfCEP.getText());
        objEndereco.setComplemento(stfComplemento.getText());
        objEndereco.setPontoReferencia(stfPontoReferencia.getText());
        objAgenciaFazendaria.setEndereco(objEndereco);

        // Inclui Contato
        objContato.setTelefo(stfTelefone.getText());
        objContato.setFax(stfFax.getText());
        objContato.setCaixaPostal(stfCaixaPostal.getText());
        objContato.setEmail(stfEmail.getText());
        objAgenciaFazendaria.setContato(objContato);

        return objAgenciaFazendaria;
    }

    private void limparCampos() {
        // Limpa dados Agencia
        stfSigla.setText("");
        stfNome.setText("");
        stfUnidadeSuperior.setText("");
        stfArea.setText("");
        stfOrgao.setText("");
        stfResponsavel.setText("");

        // Limpa dados EndereÃ§o
        stfLogradouro.setText("");
        stfNumero.setText("");
        stfBairro.setText("");
        stfMunicipio.setText("");
        stfUF.setText("");
        stfCEP.setText("");
        stfComplemento.setText("");
        stfPontoReferencia.setText("");

        // Limpa dados Contato
        stfTelefone.setText("");
        stfFax.setText("");
        stfCaixaPostal.setText("");
        stfEmail.setText("");
        
        this.montaTelaPesquisa();
    }

    private void povoaCampos(ModeloAgenciaFazendaria objAgenciaFazendaria) {
        // Povoa Agencia
        stfSigla.setText(objAgenciaFazendaria.getSigla());
        stfNome.setText(objAgenciaFazendaria.getNome());
        stfUnidadeSuperior.setText(objAgenciaFazendaria.getUnidadeSuperior());
        stfArea.setText(objAgenciaFazendaria.getArea());
        stfOrgao.setText(objAgenciaFazendaria.getOrgao());
        stfResponsavel.setText(objAgenciaFazendaria.getResponsavel());

        // Povoa EndereÃ§o
        stfLogradouro.setText(objAgenciaFazendaria.getEndereco().getLogradouro());
        stfNumero.setText(objAgenciaFazendaria.getEndereco().getNumero());
        stfBairro.setText(objAgenciaFazendaria.getEndereco().getBairro());
        stfMunicipio.setText(objAgenciaFazendaria.getEndereco().getMunicipio());
        stfUF.setText(objAgenciaFazendaria.getEndereco().getUf());
        stfCEP.setText(objAgenciaFazendaria.getEndereco().getCep());
        stfComplemento.setText(objAgenciaFazendaria.getEndereco().getComplemento());
        stfPontoReferencia.setText(objAgenciaFazendaria.getEndereco().getPontoReferencia());

        // Limpa dados Contato
        stfTelefone.setText(objAgenciaFazendaria.getContato().getTelefo());
        stfFax.setText(objAgenciaFazendaria.getContato().getFax());
        stfCaixaPostal.setText(objAgenciaFazendaria.getContato().getCaixaPostal());
        stfEmail.setText(objAgenciaFazendaria.getContato().getEmail());
    }
}
