/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.util.scorsatto.impressao.SImprimirRelatorio;
import br.com.util.scorsatto.impressao.SParametrosImpressao;
import control.ControleAgenciaFazendaria;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.ModeloAgenciaFazendaria;
import model.ModeloContato;
import model.ModeloEndereco;

/**
 *
 * @author Scorsatto
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<ModeloAgenciaFazendaria> lstAgenciaFazendaria;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }
        initComponents();
        setLocationRelativeTo(null);
        atualizarComboBox();

        setIconImage(new ImageIcon(getClass().getResource("/image/tag.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbRemetente = new javax.swing.JComboBox<>();
        jcbDestinatario = new javax.swing.JComboBox<>();
        btnImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        stfConteudo = new br.com.util.scorsatto.componentes.STextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEFAZ - Endereços");
        setResizable(false);

        jLabel1.setText("Remetente:");

        jLabel2.setText("Destinatário:");

        jcbRemetente.setNextFocusableComponent(jcbDestinatario);

        jcbDestinatario.setNextFocusableComponent(stfConteudo);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer2.png"))); // NOI18N
        btnImprimir.setNextFocusableComponent(jcbRemetente);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel3.setText("Conteúdo:");

        stfConteudo.setSTamanhoMax(50);
        stfConteudo.setSTipoTexto(br.com.util.scorsatto.genericos.SPlainDocument.TipoTexto.LIVRE);
        stfConteudo.setNextFocusableComponent(btnImprimir);

        jMenu1.setText("Cadastro");

        jMenuItem1.setText("Endereço");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Sobre");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Idealizador");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDestinatario, 0, 424, Short.MAX_VALUE)
                    .addComponent(stfConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbRemetente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbRemetente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stfConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaEndereco tela = new TelaEndereco(this, true);
        tela.setVisible(true);

        if (tela.atualizarDados()) {
            atualizarComboBox();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        ModeloAgenciaFazendaria remetente = lstAgenciaFazendaria.get(jcbRemetente.getSelectedIndex());

        ModeloAgenciaFazendaria destinatario = lstAgenciaFazendaria.get(jcbDestinatario.getSelectedIndex());

        SParametrosImpressao parametrosImpressao = new SParametrosImpressao();

        Map<String, Object> parametros = new HashMap<>();
        parametros.put("oDestinatario", getRemetenteDestinatario(remetente, "Remetente"));
        parametros.put("oEndereco", getEndereco(remetente));
        parametros.put("oContato", getContato(remetente));

        parametros.put("dDestinatario", getRemetenteDestinatario(destinatario, "Destinatário"));
        parametros.put("dEndereco", getEndereco(destinatario));
        parametros.put("dContato", getContato(destinatario));
        parametros.put("conteudo", stfConteudo.getText());
        
        parametrosImpressao.setPathRelatorio("relatorio/relatorio.jasper");

        parametrosImpressao.setParametros(parametros);
        parametrosImpressao.setMaximizado(true);
        parametrosImpressao.setTitulo("Impressão de Endereços");

        new SImprimirRelatorio().imprimir(parametrosImpressao);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new TelaSobre().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JComboBox<String> jcbDestinatario;
    private javax.swing.JComboBox<String> jcbRemetente;
    private br.com.util.scorsatto.componentes.STextField stfConteudo;
    // End of variables declaration//GEN-END:variables

    private void atualizarComboBox() {

        this.jcbRemetente.removeAllItems();
        this.jcbDestinatario.removeAllItems();

        this.lstAgenciaFazendaria = new ControleAgenciaFazendaria().pesquisaAgenciaFazendaria("", "sigla_uni");

        for (int i = 0; i < this.lstAgenciaFazendaria.size(); i++) {
            this.jcbRemetente.addItem(this.lstAgenciaFazendaria.get(i).getSigla() + " - " + this.lstAgenciaFazendaria.get(i).getNome());
            this.jcbDestinatario.addItem(this.lstAgenciaFazendaria.get(i).getSigla() + " - " + this.lstAgenciaFazendaria.get(i).getNome());
        }
    }

    private String getRemetenteDestinatario(ModeloAgenciaFazendaria objAgenciaFazendaria, String remetenteDestinatario) {
        String retorno = "<b>" + remetenteDestinatario + ":</b>";

        retorno += "\n" + objAgenciaFazendaria.getSigla() + " - " + objAgenciaFazendaria.getNome();
        retorno += "\n" + objAgenciaFazendaria.getResponsavel();

        return retorno;
    }

    private String getEndereco(ModeloAgenciaFazendaria objAgenciaFazendaria) {
        String retorno = "<b>Endereço:</b>";

        ModeloEndereco objEndereco = objAgenciaFazendaria.getEndereco();

        retorno += "\n" + objEndereco.getLogradouro() + ", " + objEndereco.getNumero() + ", " + objEndereco.getBairro() + ".";
        retorno += "\n" + objEndereco.getMunicipio() + "-" + objEndereco.getUf() + ", " + objEndereco.getCep() + ".";

        if (!objEndereco.getComplemento().isEmpty()) {
            retorno += "\nComplemento: " + objEndereco.getComplemento();
        }

        if (!objEndereco.getPontoReferencia().isEmpty()) {
            retorno += "\nPonto de Referencia: " + objEndereco.getPontoReferencia();
        }

        return retorno;
    }

    private String getContato(ModeloAgenciaFazendaria objAgenciaFazendaria) {
        String retorno = "";

        ModeloContato objContato = objAgenciaFazendaria.getContato();

        if (!objContato.getTelefo().isEmpty()) {
            retorno += "\nTelefone: " + objContato.getTelefo();
        }

        if (!objContato.getFax().isEmpty()) {
            retorno += "\nFax: " + objContato.getFax();
        }

        if (!objContato.getEmail().isEmpty()) {
            retorno += "\nE-mail: " + objContato.getEmail();
        }

        if(!retorno.isEmpty())
            retorno = "<b>Contato:</b>" + retorno;
            
        return retorno;
    }
}
